export const listData = [
  {
    propertyName: "Symon Lokes",
    location: "Mumbai",
    price: 30000,
    rating: 3,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras gravida egestas hendrerit. Etiam nec pretium velit. Maecenas nec magna id velit pellentesque scelerisque a luctus ipsum. Integer in ornare ex, vel accumsan nisl. Suspendisse efficitur dignissim nulla, ac ultricies diam varius at.",
    img: "https://images.unsplash.com/photo-1592595896551-12b371d546d5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8cmVhbCUyMGVzdGF0ZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    propertyName: "Symon Lokes",
    location: "Mumbai",
    price: 30000,
    rating: 3,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras gravida egestas hendrerit. Etiam nec pretium velit. Maecenas nec magna id velit pellentesque scelerisque a luctus ipsum. Integer in ornare ex, vel accumsan nisl. Suspendisse efficitur dignissim nulla, ac ultricies diam varius at.",
    img: "https://images.unsplash.com/photo-1592595896551-12b371d546d5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8cmVhbCUyMGVzdGF0ZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    propertyName: "Symon Lokes",
    location: "Mumbai",
    price: 30000,
    rating: 3,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras gravida egestas hendrerit. Etiam nec pretium velit. Maecenas nec magna id velit pellentesque scelerisque a luctus ipsum. Integer in ornare ex, vel accumsan nisl. Suspendisse efficitur dignissim nulla, ac ultricies diam varius at.",
    img: "https://images.unsplash.com/photo-1592595896551-12b371d546d5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8cmVhbCUyMGVzdGF0ZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    propertyName: "Symon Lokes",
    location: "Mumbai",
    price: 30000,
    rating: 3,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras gravida egestas hendrerit. Etiam nec pretium velit. Maecenas nec magna id velit pellentesque scelerisque a luctus ipsum. Integer in ornare ex, vel accumsan nisl. Suspendisse efficitur dignissim nulla, ac ultricies diam varius at.",
    img: "https://images.unsplash.com/photo-1592595896551-12b371d546d5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8cmVhbCUyMGVzdGF0ZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    propertyName: "Symon Lokes",
    location: "Mumbai",
    price: 30000,
    rating: 3,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras gravida egestas hendrerit. Etiam nec pretium velit. Maecenas nec magna id velit pellentesque scelerisque a luctus ipsum. Integer in ornare ex, vel accumsan nisl. Suspendisse efficitur dignissim nulla, ac ultricies diam varius at.",
    img: "https://images.unsplash.com/photo-1592595896551-12b371d546d5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8cmVhbCUyMGVzdGF0ZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    propertyName: "Symon Lokes",
    location: "Mumbai",
    price: 30000,
    rating: 3,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras gravida egestas hendrerit. Etiam nec pretium velit. Maecenas nec magna id velit pellentesque scelerisque a luctus ipsum. Integer in ornare ex, vel accumsan nisl. Suspendisse efficitur dignissim nulla, ac ultricies diam varius at.",
    img: "https://images.unsplash.com/photo-1592595896551-12b371d546d5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8cmVhbCUyMGVzdGF0ZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
  },
];
