export const listData = [
  {
    id:1,
    propertyName: "Symon Lokes",
    location: "Mumbai",
    price: 30000,
    rating: 3,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras gravida egestas hendrerit. Etiam nec pretium velit. Maecenas nec magna id velit pellentesque scelerisque a luctus ipsum. Integer in ornare ex, vel accumsan nisl. Suspendisse efficitur dignissim nulla, ac ultricies diam varius at.",
    img: "https://images.unsplash.com/photo-1592595896551-12b371d546d5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8cmVhbCUyMGVzdGF0ZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    id:2,
    propertyName: "Pedro Balm",
    location: "Goa",
    price: 4000,
    rating: 4.5,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras gravida egestas hendrerit. Etiam nec pretium velit. Maecenas nec magna id velit pellentesque scelerisque a luctus ipsum. Integer in ornare ex, vel accumsan nisl. Suspendisse efficitur dignissim nulla, ac ultricies diam varius at.",
    img: "https://images.unsplash.com/photo-1592595896551-12b371d546d5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8cmVhbCUyMGVzdGF0ZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    id:3,
    propertyName: "Jetty lum",
    location: "Delhi",
    price: 7500,
    rating: 5,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras gravida egestas hendrerit. Etiam nec pretium velit. Maecenas nec magna id velit pellentesque scelerisque a luctus ipsum. Integer in ornare ex, vel accumsan nisl. Suspendisse efficitur dignissim nulla, ac ultricies diam varius at.",
    img: "https://images.unsplash.com/photo-1592595896551-12b371d546d5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8cmVhbCUyMGVzdGF0ZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    id:4,
    propertyName: "Dom Mann",
    location: "Bengalore",
    price: 30000,
    rating: 3.5,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras gravida egestas hendrerit. Etiam nec pretium velit. Maecenas nec magna id velit pellentesque scelerisque a luctus ipsum. Integer in ornare ex, vel accumsan nisl. Suspendisse efficitur dignissim nulla, ac ultricies diam varius at.",
    img: "https://images.unsplash.com/photo-1592595896551-12b371d546d5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8cmVhbCUyMGVzdGF0ZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    id:5,
    propertyName: "Port Lukas",
    location: "Port Blair",
    price: 80000,
    rating: 5,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras gravida egestas hendrerit. Etiam nec pretium velit. Maecenas nec magna id velit pellentesque scelerisque a luctus ipsum. Integer in ornare ex, vel accumsan nisl. Suspendisse efficitur dignissim nulla, ac ultricies diam varius at.",
    img: "https://images.unsplash.com/photo-1592595896551-12b371d546d5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8cmVhbCUyMGVzdGF0ZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    id:6,
    propertyName: "Ocean Terrace",
    location: "Mumbai",
    price: 50000,
    rating: 3,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras gravida egestas hendrerit. Etiam nec pretium velit. Maecenas nec magna id velit pellentesque scelerisque a luctus ipsum. Integer in ornare ex, vel accumsan nisl. Suspendisse efficitur dignissim nulla, ac ultricies diam varius at.",
    img: "https://images.unsplash.com/photo-1592595896551-12b371d546d5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8cmVhbCUyMGVzdGF0ZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
  },
];
